version: '3'
services:
  postgres:
    build: ./postgres
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}

  node:
    image: node:14.17.0
    restart: unless-stopped
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    expose:
      - '${NODE_PORT}'
    environment:
      API_URL: ${API_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
    depends_on:
      - postgres
    command: node ./express/server.js
    working_dir: /app
    volumes:
      - ./:/app
